name: Flask Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
      
    - name: Start services with Docker Compose
      run: |
        docker-compose up -d
        # Wait for services to be fully up and running
        sleep 30
    
    - name: Check running containers
      run: docker ps
    
    - name: Test API Endpoints
      run: |
        curl -s http://localhost:5000/ | grep "Hello from Flask Backend!"
        curl -s http://localhost:5000/api/users | grep "HOMER"
